export const mockData = {
  Status: "success",
  ResponseCode: 200,
  ResponseMessage: "Items fetched successfully",
  Data: [
    {
      itemId: "drink1",
      itemCode: 201,
      itemName: "Coca Cola",
      itemDescription: "A classic carbonated soft drink.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["soda", "cola", "beverage"],
      itemRating: 5,
      itemImageUrl:
        "https://media.istockphoto.com/id/458464735/photo/coke.jpg?s=1024x1024&w=is&k=20&c=Fgw7bpBiVsaVnhun9uNodZhXEJVCnLLbwKMFj7p-mCk=",
    },
    {
      itemId: "drink2",
      itemCode: 202,
      itemName: "Pepsi",
      itemDescription: "A popular carbonated cola beverage.",
      itemPrice: 1.89,
      itemCategory: "Drinks",
      itemTags: ["soda", "cola", "beverage"],
      itemRating: 4,
      itemImageUrl:
        "https://images.unsplash.com/photo-1531384370597-8590413be50a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      itemId: "drink3",
      itemCode: 203,
      itemName: "Sprite",
      itemDescription: "A refreshing lemon-lime soda.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["soda", "lemon-lime", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/458716383/photo/sprite-can-on-white.jpg?s=612x612&w=0&k=20&c=85dIMCB5r97C7YRYdx9ZicKTtjYm527DXulfjD1D5fY=",
    },
    {
      itemId: "drink4",
      itemCode: 204,
      itemName: "Mountain Dew",
      itemDescription: "A citrus-flavored soft drink.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["soda", "citrus", "beverage"],
      itemRating: 4.5,
      itemImageUrl:
        "https://media.istockphoto.com/id/537663019/photo/can-of-mountain-dew-drink-isolated-on-white.jpg?s=612x612&w=0&k=20&c=Fzi0WODC6el1XFWiITOlp0UUS2f03GzFYqnoKHM1OK8=",
    },
    {
      itemId: "drink5",
      itemCode: 205,
      itemName: "7UP",
      itemDescription: "Crisp and clean lemon-lime soda.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["soda", "lemon-lime", "beverage"],
      itemRating: 4.1,
      itemImageUrl:
        "https://media.istockphoto.com/id/531417466/photo/can-of-7up.jpg?s=612x612&w=0&k=20&c=BDzgqR0ty5_b4V8ttg77l190hyY07jbo30vBwnBGOVU=",
    },
    {
      itemId: "snack1",
      itemCode: 301,
      itemName: "Lays Classic",
      itemDescription: "Classic potato chips.",
      itemPrice: 1.49,
      itemCategory: "Snacks",
      itemTags: ["chips", "potato", "snack"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/458944403/photo/lays-classic-potato-chips-open-bag.jpg?s=612x612&w=0&k=20&c=QCfo64RaHXdkmgdNkNjjxJJ_0JO5qUsXipxzcUM8Ztg=",
    },
    {
      itemId: "snack2",
      itemCode: 302,
      itemName: "Doritos Nacho Cheese",
      itemDescription: "Cheese flavored tortilla chips.",
      itemPrice: 1.69,
      itemCategory: "Snacks",
      itemTags: ["chips", "cheese", "snack"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/516035904/photo/dorito-chips.jpg?s=612x612&w=0&k=20&c=oQLuHQi75gP09EecIFf3hEVTRAaLPm99Bf5qHfWXDN4=",
    },
    {
      itemId: "snack3",
      itemCode: 303,
      itemName: "Cheetos Crunchy",
      itemDescription: "Cheese flavored crunchy snacks.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["cheese", "crunchy", "snack"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/499621987/photo/cheetos-crunchy-snack.jpg?s=612x612&w=0&k=20&c=uVLL4CLDLZ-zduwBbbBvwQR7fGTb881yfZIX9l5KJpA=",
    },
    {
      itemId: "snack4",
      itemCode: 304,
      itemName: "Ruffles Cheddar & Sour Cream",
      itemDescription: "Potato chips with cheddar and sour cream flavor.",
      itemPrice: 1.89,
      itemCategory: "Snacks",
      itemTags: ["chips", "cheddar", "sour cream"],
      itemRating: 4.1,
      itemImageUrl:
        "https://media.istockphoto.com/id/474436146/photo/delicious-mac-and-cheese.jpg?s=612x612&w=0&k=20&c=qmPOjhsa3N2jec3mDTR1Y_JMKzbZE23gx4zaLfhGRzA=",
    },
    {
      itemId: "snack5",
      itemCode: 305,
      itemName: "Snickers",
      itemDescription: "Chocolate bar with caramel and peanuts.",
      itemPrice: 1.99,
      itemCategory: "Snacks",
      itemTags: ["chocolate", "caramel", "peanuts"],
      itemRating: 4.5,
      itemImageUrl:
        "https://media.istockphoto.com/id/529240903/photo/snickers-chocolate-bar-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=IJG7PzXzMXAU2-PHrfI4gKZgPJqqVOxDxvLLEv9QwTo=",
    },
    {
      itemId: "snack6",
      itemCode: 306,
      itemName: "Kit Kat",
      itemDescription: "Chocolate covered wafer bar.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["chocolate", "wafer", "snack"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/458701489/photo/kitkat-chocolate-candy-bar-unwrapped.jpg?s=612x612&w=0&k=20&c=qB0HgAfa1iAzjCKx6Wj3u5iaTFV65A1umtXFq0ZM5PA=",
    },
    {
      itemId: "snack7",
      itemCode: 307,
      itemName: "Twix",
      itemDescription: "Chocolate bar with biscuit and caramel.",
      itemPrice: 1.89,
      itemCategory: "Snacks",
      itemTags: ["chocolate", "biscuit", "caramel"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/537889421/photo/twix-cookie-bars-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=wIcT2Vptg50Y7STggCwFqQ50Q1yfuA01D-Fs13znI_s=",
    },
    {
      itemId: "snack8",
      itemCode: 308,
      itemName: "Ritz Crackers",
      itemDescription: "Buttery round crackers.",
      itemPrice: 1.69,
      itemCategory: "Snacks",
      itemTags: ["crackers", "buttery", "snack"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/458673257/photo/ritz-crackers.jpg?s=612x612&w=0&k=20&c=X2D9ucJ7MpzizHoSAZsRFtuW0bhvLUetUReyFCjfWN0=",
    },
    {
      itemId: "snack9",
      itemCode: 309,
      itemName: "Pop-Tarts",
      itemDescription: "Toaster pastries filled with various flavors.",
      itemPrice: 1.99,
      itemCategory: "Snacks",
      itemTags: ["pastries", "breakfast", "snack"],
      itemRating: 4.1,
      itemImageUrl:
        "https://media.istockphoto.com/id/458685821/photo/pop-tarts.jpg?s=612x612&w=0&k=20&c=CA8OhICULX8j7VrtjIPqzTobheG-9xk9SEm-PcCKm40=",
    },
    {
      itemId: "snack10",
      itemCode: 310,
      itemName: "Nature Valley Granola Bars",
      itemDescription: "Crunchy granola bars with oats and honey.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["granola bars", "oats", "snack"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/1363327132/photo/woman-holding-a-cereal-bar.jpg?s=612x612&w=0&k=20&c=vCsS9h8lzpO1btmki_ddSN_9JbCNOkXdnGefJ4WtUZk=",
    },
    {
      itemId: "snack11",
      itemCode: 311,
      itemName: "Oreo Cookies",
      itemDescription: "Chocolate sandwich cookies.",
      itemPrice: 1.89,
      itemCategory: "Snacks",
      itemTags: ["cookies", "chocolate", "snack"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/458552725/photo/oreo-cookies.jpg?s=612x612&w=0&k=20&c=Fqx8l0f4alo7-OopsrSc_zKexteBTVSQvIuh1RrSyOM=",
    },
    {
      itemId: "snack12",
      itemCode: 312,
      itemName: "Nestle Toll House Chocolate Chip Cookies",
      itemDescription: "Classic chocolate chip cookies.",
      itemPrice: 1.99,
      itemCategory: "Snacks",
      itemTags: ["cookies", "chocolate chip", "snack"],
      itemRating: 4.5,
      itemImageUrl:
        "https://media.istockphoto.com/id/482994446/photo/home-style-cookies.jpg?s=612x612&w=0&k=20&c=7SoZt3_6Jr15SE7XEupHbFQYl9KHreBENl8jVlbfs6w=",
    },
    {
      itemId: "snack13",
      itemCode: 313,
      itemName: "Hershey's Chocolate Bar",
      itemDescription: "Classic milk chocolate bar.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["chocolate", "milk chocolate", "snack"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/458129279/photo/oh-henry-chocolate-candy-bar-unwrapped.jpg?s=612x612&w=0&k=20&c=zkKmClMOI0LyNGV0LYPY0z0rCnS3lFOrP_T-S1dtL3Y=",
    },
    {
      itemId: "snack14",
      itemCode: 314,
      itemName: "Gummy Bears",
      itemDescription: "Assorted fruit-flavored gummy candies.",
      itemPrice: 1.69,
      itemCategory: "Snacks",
      itemTags: ["candy", "gummy bears", "assorted"],
      itemRating: 4.1,
      itemImageUrl:
        "https://media.istockphoto.com/id/2054898644/vector/cartoon-gummy-sweets-packages-colorful-jelly-gum-candies-different-shapes-and-flavors-juicy.jpg?s=612x612&w=0&k=20&c=LlEMPTJVbOfzA8JJm1UzU90DQ9j0uarhIjcqxdsNw0c=",
    },
    {
      itemId: "snack15",
      itemCode: 315,
      itemName: "M&M's",
      itemDescription: "Colorful milk chocolate candies.",
      itemPrice: 1.89,
      itemCategory: "Snacks",
      itemTags: ["candy", "chocolate", "milk chocolate"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/458254697/photo/m-amp-ms-milk-chocolate-candies.jpg?s=612x612&w=0&k=20&c=Rr7sDZq7oGmKdaBOlSe3dwhXKjwScwh9cSII47C9cP8=",
    },
    {
      itemId: "snack16",
      itemCode: 316,
      itemName: "Sour Patch Kids",
      itemDescription: "Sour then sweet candy.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["candy", "sour", "sweet"],
      itemRating: 4.2,
      itemImageUrl:
      "https://media.istockphoto.com/id/813648418/vector/eye-drop-vector.jpg?s=612x612&w=0&k=20&c=GhtSQ2Eft4TJy4vub1ktJkzFj6fqxG0BKNzX6A1qL88=",
    },
    {
      itemId: "snack17",
      itemCode: 317,
      itemName: "Haribo Goldbears",
      itemDescription: "Chewy goldbears with fruity flavors.",
      itemPrice: 1.99,
      itemCategory: "Snacks",
      itemTags: ["candy", "goldbears", "fruity"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/1156681452/vector/realistic-detailed-3d-color-blank-foil-pack-candies-template-mockup-set-vector.jpg?s=612x612&w=0&k=20&c=x-9WGgWFFGMvCKb87b48L-JqmVP_ZoGTHIAaazqM_3U=",
    },
    {
      itemId: "snack18",
      itemCode: 318,
      itemName: "Reese's Peanut Butter Cups",
      itemDescription: "Chocolate covered peanut butter cups.",
      itemPrice: 1.89,
      itemCategory: "Snacks",
      itemTags: ["chocolate", "peanut butter", "cups"],
      itemRating: 4.5,
      itemImageUrl:
      "https://media.istockphoto.com/id/458129279/photo/oh-henry-chocolate-candy-bar-unwrapped.jpg?s=612x612&w=0&k=20&c=zkKmClMOI0LyNGV0LYPY0z0rCnS3lFOrP_T-S1dtL3Y=",
    },
    {
      itemId: "snack19",
      itemCode: 319,
      itemName: "Airheads",
      itemDescription: "Assorted fruit-flavored taffy bars.",
      itemPrice: 1.79,
      itemCategory: "Snacks",
      itemTags: ["candy", "taffy", "assorted"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/813648418/vector/eye-drop-vector.jpg?s=612x612&w=0&k=20&c=GhtSQ2Eft4TJy4vub1ktJkzFj6fqxG0BKNzX6A1qL88=",
    },
    {
      itemId: "snack20",
      itemCode: 320,
      itemName: "Popcorn",
      itemDescription: "Classic buttered popcorn.",
      itemPrice: 1.69,
      itemCategory: "Snacks",
      itemTags: ["popcorn", "buttered", "snack"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/1306733816/photo/popcorn-packet-on-black-background.jpg?s=612x612&w=0&k=20&c=gkTWXbPTv2fK0Vef5tkKz68gOKLnN5W9jqaXJVxtDMI=",
    },
    {
      itemId: "drink6",
      itemCode: 206,
      itemName: "Fanta",
      itemDescription: "A fruity orange soda.",
      itemPrice: 1.69,
      itemCategory: "Drinks",
      itemTags: ["soda", "orange", "beverage"],
      itemRating: 4.0,
      itemImageUrl:
        "https://media.istockphoto.com/id/509533066/photo/fanta-orange-can.jpg?s=612x612&w=0&k=20&c=sbii6ppPvyuny-v0mx9xizy0QppblYH3sEvPLBr31tA=",
    },
    {
      itemId: "drink7",
      itemCode: 207,
      itemName: "Dr. Pepper",
      itemDescription: "A unique blend of 23 flavors.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["soda", "flavors", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/458635091/photo/dr-pepper-on-an-isolated-white-background.jpg?s=612x612&w=0&k=20&c=g3scQZuw3hcKfVOFZodOoioW7yLVBMCGQCzF3vlYHJI=",
    },
    {
      itemId: "drink8",
      itemCode: 208,
      itemName: "Red Bull",
      itemDescription: "Energy drink with caffeine.",
      itemPrice: 2.49,
      itemCategory: "Drinks",
      itemTags: ["energy drink", "caffeine", "beverage"],
      itemRating: 4.5,
      itemImageUrl:
        "https://img.freepik.com/premium-photo/product-packaging-mockup-photo-soda-can-with-droplets-water-studio-advertising-photoshoot_1061358-76210.jpg?w=740",
    },
    {
      itemId: "drink9",
      itemCode: 209,
      itemName: "Monster Energy",
      itemDescription: "Energy drink with a bold flavor.",
      itemPrice: 2.29,
      itemCategory: "Drinks",
      itemTags: ["energy drink", "bold flavor", "beverage"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/459257189/photo/can-of-monster-energy-drink.jpg?s=612x612&w=0&k=20&c=PjLm5LdKnqR-rSRQjzqY_96kOkvv2Mypulf84L9lCN8=",
    },
    {
      itemId: "drink10",
      itemCode: 210,
      itemName: "Arizona Iced Tea",
      itemDescription: "Iced tea with natural flavors.",
      itemPrice: 1.49,
      itemCategory: "Drinks",
      itemTags: ["iced tea", "natural flavors", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
        "https://plus.unsplash.com/premium_photo-1663853293405-5e2f30f03d34?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8QXJpem9uYSUyMEljZWQlMjBUZWF8ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink11",
      itemCode: 211,
      itemName: "Gatorade",
      itemDescription: "Thirst quencher sports drink.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["sports drink", "thirst quencher", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
        "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGhpcnN0JTIwcXVlbmNoZXIlMjBzcG9ydHMlMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      itemId: "drink12",
      itemCode: 212,
      itemName: "Snapple",
      itemDescription: "Refreshing tea and juice drink.",
      itemPrice: 1.89,
      itemCategory: "Drinks",
      itemTags: ["tea", "juice", "beverage"],
      itemRating: 4.4,
      itemImageUrl:
        "https://img.freepik.com/premium-photo/elegant-cocktails-with-floral-garnish_711700-17427.jpg?ga=GA1.1.1271048782.1719312153&semt=ais_user",
    },
    {
      itemId: "drink13",
      itemCode: 213,
      itemName: "Starbucks Frappuccino",
      itemDescription: "Coffee drink with creamy blend.",
      itemPrice: 2.29,
      itemCategory: "Drinks",
      itemTags: ["coffee", "creamy", "beverage"],
      itemRating: 4.5,
      itemImageUrl:
        "https://images.unsplash.com/photo-1657657168551-c2cde84f4492?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U3RhcmJ1Y2tzJTIwRnJhcHB1Y2Npbm98ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink14",
      itemCode: 214,
      itemName: "Tropicana Orange Juice",
      itemDescription: "Pure premium orange juice.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["orange juice", "premium", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
        "https://plus.unsplash.com/premium_photo-1675667390417-d9d23160f4a6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VHJvcGljYW5hJTIwT3JhbmdlJTIwSnVpY2V8ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink15",
      itemCode: 215,
      itemName: "Minute Maid Lemonade",
      itemDescription: "Classic lemonade made with real lemons.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["lemonade", "real lemons", "beverage"],
      itemRating: 4.1,
      itemImageUrl:
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGhpcnN0JTIwcXVlbmNoZXIlMjBzcG9ydHMlMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      itemId: "drink16",
      itemCode: 216,
      itemName: "San Pellegrino Sparkling Water",
      itemDescription: "Naturally flavored sparkling water.",
      itemPrice: 1.89,
      itemCategory: "Drinks",
      itemTags: ["sparkling water", "flavored", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
      "https://plus.unsplash.com/premium_photo-1663853293405-5e2f30f03d34?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8QXJpem9uYSUyMEljZWQlMjBUZWF8ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink17",
      itemCode: 217,
      itemName: "Perrier Carbonated Mineral Water",
      itemDescription: "Sparkling mineral water.",
      itemPrice: 1.69,
      itemCategory: "Drinks",
      itemTags: ["mineral water", "sparkling", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGhpcnN0JTIwcXVlbmNoZXIlMjBzcG9ydHMlMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      itemId: "drink18",
      itemCode: 218,
      itemName: "Evian Natural Spring Water",
      itemDescription: "Natural spring water.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["spring water", "natural", "beverage"],
      itemRating: 4.1,
      itemImageUrl:
      "https://img.freepik.com/premium-photo/product-packaging-mockup-photo-soda-can-with-droplets-water-studio-advertising-photoshoot_1061358-76210.jpg?w=740",
    },
    {
      itemId: "drink19",
      itemCode: 219,
      itemName: "Vitaminwater",
      itemDescription: "Enhanced water with vitamins.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["enhanced water", "vitamins", "beverage"],
      itemRating: 4.0,
      itemImageUrl:
      "https://media.istockphoto.com/id/459458845/photo/set-of-drink-cans.jpg?s=612x612&w=0&k=20&c=V4E1HR-u0nbwolr3GXkkee80L8wC3XkYk-acuQEVAdU=",
    },
    {
      itemId: "drink20",
      itemCode: 220,
      itemName: "Powerade",
      itemDescription: "Sports drink for hydration.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["sports drink", "hydration", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
      "https://media.istockphoto.com/id/458635091/photo/dr-pepper-on-an-isolated-white-background.jpg?s=612x612&w=0&k=20&c=g3scQZuw3hcKfVOFZodOoioW7yLVBMCGQCzF3vlYHJI=",
    },
    {
      itemId: "drink21",
      itemCode: 221,
      itemName: "Kombucha",
      itemDescription: "Fermented tea drink with probiotics.",
      itemPrice: 2.49,
      itemCategory: "Drinks",
      itemTags: ["kombucha", "fermented tea", "probiotics"],
      itemRating: 4.4,
      itemImageUrl:
      "https://img.freepik.com/premium-photo/elegant-cocktails-with-floral-garnish_711700-17427.jpg?ga=GA1.1.1271048782.1719312153&semt=ais_user",
    },
    {
      itemId: "drink22",
      itemCode: 222,
      itemName: "Yerba Mate",
      itemDescription: "Traditional South American tea.",
      itemPrice: 2.29,
      itemCategory: "Drinks",
      itemTags: ["yerba mate", "south american tea", "caffeine"],
      itemRating: 4.5,
      itemImageUrl:
      "https://plus.unsplash.com/premium_photo-1675667390417-d9d23160f4a6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VHJvcGljYW5hJTIwT3JhbmdlJTIwSnVpY2V8ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink23",
      itemCode: 223,
      itemName: "Cranberry Juice",
      itemDescription: "100% cranberry juice.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["cranberry juice", "100%", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
        "https://images.unsplash.com/photo-1606767341197-2de041e9ad9d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8S29tYnVjaGElMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      itemId: "drink24",
      itemCode: 224,
      itemName: "Coconut Water",
      itemDescription: "Pure coconut water.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["coconut water", "pure", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
      "https://plus.unsplash.com/premium_photo-1663853293405-5e2f30f03d34?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8QXJpem9uYSUyMEljZWQlMjBUZWF8ZW58MHx8MHx8fDA%3D",
    },
    {
      itemId: "drink25",
      itemCode: 225,
      itemName: "Honest Tea",
      itemDescription: "Organic bottled tea.",
      itemPrice: 1.89,
      itemCategory: "Drinks",
      itemTags: ["organic", "bottled tea", "beverage"],
      itemRating: 4.1,
      itemImageUrl:
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGhpcnN0JTIwcXVlbmNoZXIlMjBzcG9ydHMlMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D",
    },
    {
      itemId: "drink26",
      itemCode: 226,
      itemName: "Guayaki Yerba Mate",
      itemDescription: "Traditional yerba mate.",
      itemPrice: 2.49,
      itemCategory: "Drinks",
      itemTags: ["yerba mate", "traditional", "south american"],
      itemRating: 4.0,
      itemImageUrl:
      "https://img.freepik.com/premium-photo/product-packaging-mockup-photo-soda-can-with-droplets-water-studio-advertising-photoshoot_1061358-76210.jpg?w=740",
    },
    {
      itemId: "drink27",
      itemCode: 227,
      itemName: "Sprite",
      itemDescription: "Crisp lemon-lime soda.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["soda", "lemon-lime", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
      "https://media.istockphoto.com/id/458716383/photo/sprite-can-on-white.jpg?s=612x612&w=0&k=20&c=85dIMCB5r97C7YRYdx9ZicKTtjYm527DXulfjD1D5fY=",
    },
    {
      itemId: "drink28",
      itemCode: 228,
      itemName: "Coca-Cola Classic",
      itemDescription: "Classic cola soft drink.",
      itemPrice: 1.89,
      itemCategory: "Drinks",
      itemTags: ["cola", "classic", "beverage"],
      itemRating: 4.4,
      itemImageUrl:
        "https://media.istockphoto.com/id/459458845/photo/set-of-drink-cans.jpg?s=612x612&w=0&k=20&c=V4E1HR-u0nbwolr3GXkkee80L8wC3XkYk-acuQEVAdU=",
    },
    {
      itemId: "drink29",
      itemCode: 229,
      itemName: "Pepsi",
      itemDescription: "Refreshing cola soft drink.",
      itemPrice: 1.79,
      itemCategory: "Drinks",
      itemTags: ["cola", "refreshing", "beverage"],
      itemRating: 4.3,
      itemImageUrl:
        "https://media.istockphoto.com/id/163983424/vector/soft-drink-bottles.jpg?s=612x612&w=0&k=20&c=RfK4al81nTuGOGQTUXLTAf7PQWuZc9HsZRBNAzAflbo=",
    },
    {
      itemId: "drink30",
      itemCode: 230,
      itemName: "Mountain Dew",
      itemDescription: "Citrus-flavored soda.",
      itemPrice: 1.99,
      itemCategory: "Drinks",
      itemTags: ["soda", "citrus-flavored", "beverage"],
      itemRating: 4.2,
      itemImageUrl:
        "https://media.istockphoto.com/id/537663019/photo/can-of-mountain-dew-drink-isolated-on-white.jpg?s=612x612&w=0&k=20&c=Fzi0WODC6el1XFWiITOlp0UUS2f03GzFYqnoKHM1OK8=",
    },
  ],
};
